baseURL = "https://ameliaf5a8b8.github.io/"
languageCode = "en-gb"
title = "Amelia"
theme = "PaperMod"

enableRobotsTXT = true
enableGitInfo = true

[pagination]
  pagerSize = 10

[params]
  author = "Amelia"
  ShowReadingTime = true
  ShowWordCount = true
  ShowLastMod = true
  ShowPostNavLinks = true

  math = true

  [params.katex]
    enable = true
    macros = { "\\doteq" = "\\mathrel{\\dot{=}}" }
 
  mainSections = ["posts"]


  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/yourusername"

  [[params.socialIcons]]
    name = "email"
    url = "mailto:you@email.com"

  [params.breadcrumbs]
    enabled = true
  [params.profileMode]
    enabled = true
    title = "Amelia"
    subtitle = "Machine Learning · Mathematics · Repeat"
    imageUrl = "pfp.jpg"
    imageWidth = 200
    imageHeight = 200



[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

[markup]
  [markup.goldmark]
    unsafe = true

    [markup.goldmark.renderer]
      hardWraps = false
    
    [markup.goldmark.extensions]
      enable = true
    
      [markup.goldmark.extensions.passthrough.delimiters]
          block = [['$$', '$$']]
          inline = [['$', '$']]
